# Generated by Django 4.2.5 on 2024-08-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='workers',
            field=models.ManyToManyField(to='api.worker'),
        ),
    ]
