# Generated by Django 4.2.5 on 2024-07-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workinterval'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinterval',
            name='start_utcms',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workinterval',
            name='stop_utcms',
            field=models.BigIntegerField(null=True),
        ),
    ]
