# Generated by Django 4.2.5 on 2024-08-07 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinterval',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.worker'),
        ),
    ]
