# Generated by Django 4.2.5 on 2024-08-10 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_clientbillabletype_agreement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinterval',
            name='type',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.worktype'),
        ),
    ]
