# Generated by Django 4.2.5 on 2024-08-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_workinterval_type_invoiceitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issued',
            field=models.DateTimeField(null=True),
        ),
    ]
