# Generated by Django 4.2.5 on 2024-08-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_project_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='type',
            new_name='work_type',
        ),
    ]
