# Generated by Django 4.2.5 on 2024-08-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_type_invoiceitem_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='ymd_birth',
            field=models.DateField(null=True),
        ),
    ]
