# Generated by Django 4.2.5 on 2024-08-12 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_worker_created_worker_ymd_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.client')),
                ('invoice_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.invoiceitem')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.worker')),
            ],
        ),
    ]
