# Generated by Django 4.2.5 on 2024-08-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_workpiece'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('url', models.URLField()),
                ('work_piece', models.ManyToManyField(to='api.workpiece')),
            ],
        ),
    ]
