# Generated by Django 4.2.5 on 2024-08-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='filename',
            field=models.CharField(default='_default', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medium',
            name='name',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='medium',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
