# Generated by Django 4.2.5 on 2024-08-16 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_contentcategory_remove_workpiece_worker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_rate', models.IntegerField(default=0)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.agreement')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.worker')),
            ],
        ),
    ]
