# Generated by Django 4.2.5 on 2024-08-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_projecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='created',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
