# Generated by Django 4.2.5 on 2024-08-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_agreement_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='worker',
        ),
        migrations.AddField(
            model_name='agreement',
            name='workers',
            field=models.ManyToManyField(to='api.worker'),
        ),
    ]
