# Generated by Django 4.2.5 on 2024-08-22 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_project_finished_project_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpiece',
            name='finish',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workpiece',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.project'),
        ),
        migrations.AlterField(
            model_name='workpiece',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='WorkMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.client')),
                ('invoice_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.invoiceitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.project')),
                ('worker', models.ManyToManyField(to='api.worker')),
            ],
            options={
                'indexes': [models.Index(fields=['start'], name='api_workmil_start_ad6cc7_idx')],
            },
        ),
    ]
