# Generated by Django 4.2.5 on 2024-08-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_workpiece_finish_workpiece_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmilestone',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
