# Generated by Django 4.2.5 on 2024-08-23 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_workmilestone_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workmilestone',
            old_name='worker',
            new_name='workers',
        ),
    ]
